#!/bin/sh
jq -r '.[($ARGS.positional[0] // "test")]' --args $* <<HERE | sh
{
    "test": "echo 'Pass'",
    "lint": "find . -iname '*.json' -print -exec jq . '{}' \\\\;",
    "help": "printf \\"Usage: ./jelly [<task>]\\\\n\\\\nTasks:\\\\n\\\\n\\"; tail -r ./jelly | tail -n +2 | tail -r | tail -n +3 | sed 's/\\\\\\\\\\\\\\\\/\\\\\\\\/g' | jq -r 'keys | .[]'"
}
HERE
